service: elasticsearch-sync

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-offline-aws-eventbridge

functions:
  publishEvent:
    handler: events.publish
    events:
      - http:
          path: publish
          method: get

  consumeEvent:
    handler: events.consume
    events:
      - eventBridge:
          eventBus: marketing
          pattern:
            source:
              - acme.newsletter.campaign

custom:
  serverless-offline-aws-eventbridge:
    port: 4080 # port to run the eventbridge mock server on
    subscriberOnly: false # Set to true if the eventBridge mock is managed by another stack
    pubSubPort: 4011 # port to run the eventbridge mock server on
    debug: true # flag to show debug messages
    account: '' # account id that gets passed to the event
  serverless-offline:
    lambdaPort: 3017 # Do not use 3002 to avoid port conflict while multiple stacks are running
    httpPort: 3016